# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-e',
  'process.stdout.write(require("resolve").sync("react-native/scripts/react_native_pods.rb", {basedir: process.cwd()}))',
]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

target 'BluetoothChat' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => true,
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'BluetoothChatTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
  end
end
